apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kasse-service"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kasse-service"
  template:
    metadata:
      labels:
        app: "kasse-service"
    spec:
      containers:
        - name: "masterarbeitcluster-472f"
          image: "masterimages.azurecr.io/kasse-service.jar:latest"
          ports:
          - containerPort: 8081
