apiVersion: v1
kind: Service
metadata:
    name: "masterarbeitcluster-472f"
    labels:
        app: "masterarbeitcluster-472f"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    selector:
        app: "masterarbeitcluster-472f"